<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LabResult extends Model
{
    /** @use HasFactory<\Database\Factories\LabResultFactory> */
    use HasFactory;

    protected $fillable = [
        'id',
        'tgl_pemeriksaan',
        'nama_pasien',
        'alamat',
        'jenis_kelamin',
        'tgl_lahir',
        'umur',
        'poli',
        'status_pembayaran',
        'a_hematologi_hb',
        'a_hematologi_diffcount',
        'a_hematologi_leukosit',
        'a_hematologi_trombosit',
        'a_hematologi_ht',
        'a_hematologi_led',
        'a_hematologi_golongandarah',
        'b_kimiadarah_glukosadarah',
        'b_kimiadarah_kolesterol',
        'b_kimiadarah_asamurat',
        'c_serologi_widal_o',
        'c_serologi_widal_ao',
        'c_serologi_widal_h',
        'c_serologi_widal_ah',
        'c_serologi_dengue_iggigm',
        'c_serologi_dengue_ns1',
        'c_serologi_malaria',
        'c_serologi_syphilis',
        'c_serologi_hbsag',
        'c_serologi_hiv',
        'c_serologi_hcv',
        'c_serologi_teskehamilan',
        'd_urin_makroskopis_warna',
        'd_urin_makroskopis_kekeruhan',
        'd_urin_makroskopis_ph',
        'd_urin_makroskopis_bjurin',
        'd_urin_makroskopis_protein',
        'd_urin_makroskopis_glukosa',
        'd_urin_makroskopis_bilirubin',
        'd_urin_makroskopis_urobilinogen',
        'd_urin_makroskopis_keton',
        'd_urin_makroskopis_nitrit',
        'd_urin_makroskopis_leukosit',
        'd_urin_makroskopis_blood',
        'd_urin_makroskopis_asamaskorbat',
        'd_urin_mikroskopis_eritrosit',
        'd_urin_mikroskopis_leukosit',
        'd_urin_mikroskopis_epitel',
        'd_urin_mikroskopis_bakteri',
        'd_urin_mikroskopis_kristal',
        'd_urin_mikroskopis_silinder',
        'd_urin_mikroskopis_jamur',
        'd_urin_mikroskopis_trichomonas',
        'd_urin_mikroskopis_sprema',
        'e_sekret_vagina',
        'e_sekret_utera',
        'f_dahak_slide',
        'f_dahak_tcm',
        'g_kimiadarah2_ureum',
        'g_kimiadarah2_kreatinin',
        'g_kimiadarah2_sgot',
        'g_kimiadarah2_sgpt',
        'g_kimiadarah2_hdl',
        'g_kimiadarah2_ldl',
        'g_kimiadarah2_trigliserida',
        'h_urin2_tesnarkoba',
        'i_lainlain',
    ];
}
